CREATE DATABASE INVESTORCARE;
GO
USE INVESTORCARE;
GO

-- ==========================================
-- 1. XÓA BẢNG CŨ
-- ==========================================
DROP TABLE IF EXISTS ALERT;
DROP TABLE IF EXISTS PORTFOLIO_HOLDING;
DROP TABLE IF EXISTS PORTFOLIO;
DROP TABLE IF EXISTS SIGNAL;
DROP TABLE IF EXISTS MODEL_REGISTRY;
DROP TABLE IF EXISTS PRICE_BAR;
DROP TABLE IF EXISTS NEWS_ITEM;
DROP TABLE IF EXISTS CARE_NOTE;
DROP TABLE IF EXISTS WATCHLIST_ITEM;
DROP TABLE IF EXISTS WATCHLIST;
DROP TABLE IF EXISTS ASSET;
DROP TABLE IF EXISTS [USER];
GO

-- ==========================================
-- 2. TẠO BẢNG (Giữ nguyên cấu trúc của bạn)
-- ==========================================
CREATE TABLE [USER] (
    USER_ID INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(30),
    ROLE VARCHAR(20) DEFAULT 'User',
    STATUS VARCHAR(20) DEFAULT 'Active',
    CREATED_AT DATETIME2(0) DEFAULT GETDATE()
);

CREATE TABLE ASSET (
    ASSET_ID INT IDENTITY(1,1) PRIMARY KEY, 
    TYPE VARCHAR(10) NOT NULL CHECK (TYPE IN ('STOCK', 'GOLD', 'SILVER')),    
    SYMBOL VARCHAR(20) NOT NULL UNIQUE,
    EXCHANGE VARCHAR(50),
    NAME VARCHAR(255) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Active',
    VISIBLE BIT DEFAULT 1,
    CREATED_AT DATETIME2(0) DEFAULT GETDATE(), 
    UPDATED_AT DATETIME2(0) DEFAULT GETDATE()  
);

CREATE TABLE PRICE_BAR (
    ASSET_ID INT,
    TS DATETIME2(0) NOT NULL,
    [OPEN] DECIMAL(18, 4),
    HIGH DECIMAL(18, 4),
    LOW DECIMAL(18, 4),
    [CLOSE] DECIMAL(18, 4),
    VOLUME BIGINT,
    SOURCE VARCHAR(50),
    PRIMARY KEY (ASSET_ID, TS),
    FOREIGN KEY (ASSET_ID) REFERENCES ASSET(ASSET_ID) ON DELETE CASCADE
);

CREATE TABLE NEWS_ITEM (
    NEWS_ID INT IDENTITY(1,1) PRIMARY KEY,
    TS DATETIME NOT NULL,
    SOURCE VARCHAR(100),
    TITLE NVARCHAR(500),
    URL NVARCHAR(MAX),
    RELATED_SYMBOLS VARCHAR(255),
    SENTIMENT_SCORE DECIMAL(3, 2),
    RELEVANCE DECIMAL(3, 2)
);

CREATE TABLE MODEL_REGISTRY (
    MODEL_ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(100),
    VERSION VARCHAR(20) NOT NULL,
    ALGORITHM VARCHAR(50),
    METRICS_JSON NVARCHAR(MAX),
    FILE_PATH VARCHAR(500),
    ACTIVE_FLAG BIT DEFAULT 0
);

CREATE TABLE SIGNAL (
    SIGNAL_ID INT IDENTITY(1,1) PRIMARY KEY,
    ASSET_ID INT,
    MODEL_ID INT,
    TS DATETIME DEFAULT GETDATE(),
    RISK_SCORE DECIMAL(5, 4),
    ANOMALY_FLAG BIT,
    TREND_PROB DECIMAL(5, 4),
    EXPLANATION_TEXT NVARCHAR(MAX),
    FOREIGN KEY (ASSET_ID) REFERENCES ASSET(ASSET_ID),
    FOREIGN KEY (MODEL_ID) REFERENCES MODEL_REGISTRY(MODEL_ID)
);

CREATE TABLE PORTFOLIO (
    PORTFOLIO_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT,
    NAME VARCHAR(100),
    FOREIGN KEY (USER_ID) REFERENCES [USER](USER_ID)
);

CREATE TABLE PORTFOLIO_HOLDING (
    PORTFOLIO_ID INT,
    ASSET_ID INT,
    QTY DECIMAL(18, 4),
    AVG_COST DECIMAL(18, 4),
    PRIMARY KEY (PORTFOLIO_ID, ASSET_ID),
    FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO(PORTFOLIO_ID),
    FOREIGN KEY (ASSET_ID) REFERENCES ASSET(ASSET_ID)
);

CREATE TABLE ALERT (
    ALERT_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT,
    ASSET_ID INT,
    SIGNAL_ID INT,
    TS DATETIME DEFAULT GETDATE(),
    SEVERITY VARCHAR(20) CHECK (SEVERITY IN ('LOW', 'MEDIUM', 'HIGH')),
    MESSAGE NVARCHAR(MAX),
    STATUS VARCHAR(20) DEFAULT 'NEW' CHECK (STATUS IN ('NEW', 'READ', 'DISMISSED')),
    FOREIGN KEY (USER_ID) REFERENCES [USER](USER_ID),
    FOREIGN KEY (ASSET_ID) REFERENCES ASSET(ASSET_ID),
    FOREIGN KEY (SIGNAL_ID) REFERENCES SIGNAL(SIGNAL_ID)
);

CREATE TABLE WATCHLIST (
    WATCHLIST_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT,
    NAME NVARCHAR(100) NOT NULL,
    CREATED_AT DATETIME2(0) DEFAULT GETDATE(),
    FOREIGN KEY (USER_ID) REFERENCES [USER](USER_ID) ON DELETE CASCADE
);

CREATE TABLE WATCHLIST_ITEM (
    ITEM_ID INT IDENTITY(1,1) PRIMARY KEY,
    WATCHLIST_ID INT,
    ASSET_ID INT,
    ADDED_AT DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (WATCHLIST_ID) REFERENCES WATCHLIST(WATCHLIST_ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSET_ID) REFERENCES ASSET(ASSET_ID) ON DELETE CASCADE
);

CREATE TABLE CARE_NOTE (
    NOTE_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT,
    ASSET_ID INT,
    TITLE NVARCHAR(255) NOT NULL,
    CONTENT NVARCHAR(MAX),
    CREATED_AT DATETIME2(0) DEFAULT GETDATE(),
    UPDATED_AT DATETIME2(0) DEFAULT GETDATE(),
    FOREIGN KEY (USER_ID) REFERENCES [USER](USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSET_ID) REFERENCES ASSET(ASSET_ID) ON DELETE CASCADE
);
GO

-- ==========================================
-- 3. CHÈN DỮ LIỆU (Giữ nguyên giá trị của bạn, chỉ đổi thứ tự)
-- ==========================================

-- Chèn USER trước
INSERT INTO [USER] (USERNAME, EMAIL, PASSWORD, ROLE, STATUS)
VALUES 
('admin1', 'admin@investorcare.vn', '12345', 'Admin', 'Active'),
('admin2', 'admin@investorcare.vn', '123456', 'Admin', 'Active'),
('user1', 'user@investorcare.vn', '12345', 'User', 'Active'),
('user2', 'user@investorcare.vn', '123456', 'User', 'Active');
GO

-- Chèn ASSET (Phải có trước để PRICE_BAR không bị lỗi Foreign Key)
INSERT INTO ASSET (TYPE, SYMBOL, EXCHANGE, NAME)
VALUES
('STOCK', 'AMZN', 'NASDAQ', 'Amazon.com Inc.'),
('STOCK', 'META', 'NASDAQ', 'Meta Platforms Inc.'),
('STOCK', 'TSLA', 'NASDAQ', 'Tesla Inc.'),
('STOCK', 'NFLX', 'NASDAQ', 'Netflix Inc.');
GO

-- Chèn PRICE_BAR (Bây giờ ASSET_ID 1 đã tồn tại - chính là AMZN)
INSERT INTO PRICE_BAR 
(ASSET_ID, TS, [OPEN], HIGH, LOW, [CLOSE], VOLUME, SOURCE)
VALUES (1, GETDATE()-1, 100, 105, 95, 100, 1000000, 'TEST');

INSERT INTO PRICE_BAR 
(ASSET_ID, TS, [OPEN], HIGH, LOW, [CLOSE], VOLUME, SOURCE)
VALUES (1, GETDATE(), 110, 115, 108, 110, 1200000, 'TEST');
GO

-- Chèn MODEL
INSERT INTO MODEL_REGISTRY (NAME, VERSION, ALGORITHM, ACTIVE_FLAG)
VALUES ('VolatilityModel', '1.0', 'PercentChange', 1);

-- Chèn thêm PRICE_BAR
-- Dòng đầu tiên giữ nguyên
INSERT INTO PRICE_BAR
(ASSET_ID, TS, [OPEN], HIGH, LOW, [CLOSE], VOLUME, SOURCE)
VALUES
(1, DATEADD(minute, -1, GETDATE()), 200, 200, 200, 200, 1000, 'TEST');

-- Dòng thứ hai: Cộng thêm 1 giây để tránh trùng khóa chính với dòng trên
INSERT INTO PRICE_BAR
(ASSET_ID, TS, [OPEN], HIGH, LOW, [CLOSE], VOLUME, SOURCE)
VALUES
(1, DATEADD(second, 1, GETDATE()), 210, 210, 210, 210, 1000, 'TEST');
GO

-- Dọn dẹp và Truy vấn (Giữ nguyên các lệnh cuối của bạn)
DELETE FROM PRICE_BAR WHERE SOURCE = 'TEST';

SELECT * FROM MODEL_REGISTRY;
SELECT * FROM ASSET;
SELECT * FROM [USER];